---
title: Exercises
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---


In this course, we will be using Jupyter notebooks. These let you write and run code on a remote server using nothing more than a standard web browser. 'Jupyter' is the software framework that makes this work. Jupyter can be used to provide an interface to a variety of different programming languages, but in this course we will concentrate on Python.


 
## Getting started with python and jupyter

Some simple introductary notebooks to help you learn both notebooks and python at the same time.
We ran through some of this in our [meet-and-greet](../FirstSteps/Introduction2Python/0-CharacteristicsOfPython) with python programming 


 - [Exercise 4 - Guessing Games](Ex04/Ex4-GuessingGames)


## Python idiosyncrasies 

 - [Exercise 9 - Modules](Ex09/Ex9-Modules)
 - [Exercise 10 - Exception handling](Ex10/Ex10-Exceptions)

## Doing things with python 

Here we begin to explore the commonly used packages that are readily available in the python 
ecosystem. These exercises give you an introduction to the topic and you can dig deeper later.

 - [Exercise 11 - Numpy](Ex11/Ex11-numpy) - Go deeper into numpy/scipy with [these notebooks](../Themes/NumpyAndScipy/0-NumpyAndScipy) 
 - [Exercise 12 - Plotting](Ex12/Ex12-Plotting)
 - [Exercise 13 - Radioactive Decay](Ex13/Ex13-RadioactiveDecay)
 - [Exercise 14 - Pandas](Ex14/Ex14-PandasDatabases)
 - [Exercise 15 - More plotting](Ex15/Ex15-MorePlotting)
 - [Exercise 16 - Maps](Ex16/Ex16-Maps) - Go deeper into map making with [these notebooks](../Themes/Mapping/0-Maps_with_Cartopy)
 - [Exercise 17 - Fourier analysis and Milankovitch cycles](Ex17/Ex17-FourierAnalysis)

## More advanced material

 - [Exercise 18 - Object-oriented programming](Ex18/Ex18-Objects)
 - [Exercise 19 - differential equations](Ex19/Ex19-DifferentialEqs)
 - [Exercise 20 - Sorting](Ex20/Ex20-Sorting)

There are more [in-depth examples](../Themes/0-StartHere.md) that you can now start to work through. These will
assume you understand python and are trying to understand the programming process. 

```python

```


