name: base
channels: 
    - conda-forge
    - geo-down-under
dependencies:
    - cloudstor
    - stripy
    - litho1pt0
    - cartopy
    # - proj=7.*.        # errors with cartopy when 6.2.* is used
    # - cartopy=0.18.*
    - gdal
    - libgdal
    - obspy
    - pandas
    - pip 
    - libiconv
    - xarray
    - nodejs
    - jupytext
    - h5netcdf
    - netcdf4
    # - pip:
    #   - lavavu<1.7

