name: base
channels: 
    - conda-forge
    - geo-down-under
dependencies:
    - stripy
    - litho1pt0
    - proj>=7.0   # errors with cartopy when 6.2.* is used
    - cartopy=17.*
    - obspy
    - pandas
    - pip 
    - libiconv





