name: base
channels: 
    - conda-forge
    - geo-down-under
dependencies:
    - python=3.7
    - cloudstor
    - stripy
    - litho1pt0
    - proj=7.*.        # errors with cartopy when 6.2.* is used
    - cartopy=0.18.*
    - gdal
    - libgdal
    - obspy
    - pandas
    - pip 
    - libiconv
    - xarray
    - nodejs
    - jupytext
    - h5netcdf
    - netcdf4
    - pip:
      - lavavu<1.7

