# Conda Environment for python packages running under BINDER
name: EMSC-2022
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - pyvista[all]
  # - mpmath<=1.3
  # - mesalib
  - pandas
  - numpy
  - scipy
  - h5py
  - sympy
  - cartopy
  - obspy
  - stripy
  - xarray
  - netcdf4
  - pip
  - pip:  
    - gmsh
    - jupyterlab>=4.1
    - jupytext>=1.16.1
    - pygments>=2.17.0
    - trame-vtk
    - trame-vuetify
    - litho1pt0

  
