project:
  type: book
  output-dir: ../_build/book

book:
  title: "EMSC 2022"
  author:
    - "David Heslop"
    - "Meghan Miller"
    - "Voon Hui Lai"
    - "Louis Moresi"
  date: today
  bread-crumbs: true

  chapters:
    - index.qmd

    - part: "**Labs**"
      chapters:
        - Notebooks/LAB-week5/Week5_Lab.ipynb
        - Notebooks/LAB-week5/LAB5_Volcano_Map.ipynb
        - Notebooks/LAB-week5/LAB5_On_Demand_MapServices.ipynb
        - Notebooks/LAB-week6/LAB6-focal_mechanisms.ipynb
        - Notebooks/LAB-week6/LAB6-izmit+focal+mechanism.ipynb
        - Notebooks/LAB-week7/LAB7-Raypaths.ipynb
        - Notebooks/LAB-week7/LAB7-NZ_Earthquake.ipynb
        - Notebooks/LAB-week8/LAB8-Gutenberg-Richter.ipynb
        - Notebooks/LAB-week10/EMSC2022_sem1_2023_lowerpuna.ipynb
        - Notebooks/LAB-week10/Practical10-Part5-MogiModel.ipynb
        - Notebooks/LAB-convection/EMSC2022W11.i.ipynb
        - Notebooks/LAB-convection/EMSC2022W11.ii.ipynb
        - Notebooks/LAB-convection/EMSC2022W11.iii.ipynb
        - Notebooks/LAB-convection/EMSC2022W11.iv.ipynb
        - Notebooks/LAB-convection/EMSC2022W11.v.ipynb
        - Notebooks/LAB-convection/EMSC2022W11.vi.ipynb

    - part: "**Lectures**"
      chapters:
        - Lectures/Index.qmd
        - Lectures/Lectures-MantleDynamics.qmd

  navbar:
    search: true
    logo: assets/ANU-logo.png
    background: "#C58812"  # ANU gold
    foreground: white
    left:
      - text: "Home"
        file: index.qmd
      - text: "Slides"
        href: ../WebSlides/index.html
    right:
      - icon: github
        href: https://github.com/ANU-RSES-Education/EMSC-2022

  sidebar:
    logo: assets/AuWorldEQ.jpg
    style: "docked"
    background: light

bibliography: references.bib

execute:
  enabled: false
  allow_errors: true

format:
  html:
    theme: [cosmo, "assets/theme.scss"]
    css: assets/styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-fold: false
    linkcolor: "#C58812"
    number-sections: false

    code-links:
      - text: Open in Binder
        icon: rocket-takeoff
        href: https://mybinder.org/v2/gh/ANU-RSES-Education/EMSC-2022/HEAD
    other-links:
      - text: Wattle Site
        icon: mortarboard
        href: https://wattlecourses.anu.edu.au/course/view.php?id=36759
