# EMSC 2022 - Table of Contents

<center>
<video controls autoplay width="600">
    <source src="../Jupyterbook/Figures/Movies/etopoimageH.mp4"
            type="video/mp4">

    Sorry, your browser doesn't support embedded videos.
</video>

*The Earth's topography and bathymetry.*
</center>

Here you will find the Lab notebooks for the course, and the Mantle Dynamics Lecture slides.

If you are lost you can go back to the [wattle site for the course](https://wattlecourses.anu.edu.au/course/view.php?id=36759)

## Navigate

Use the navigation menu on the left to browse through:

- **Labs** - Practical exercises using Python and Jupyter notebooks
- **Lectures** - Mantle dynamics lecture materials and slides

## Accessing the Materials

The materials in this book are available in several ways:

- **Browse online** - Read through the materials in your web browser
- **Launch in Binder** - Click the rocket icon at the top of any notebook page to run the code interactively
- **Download** - Get the materials from the [GitHub repository](https://github.com/ANU-RSES-Education/EMSC-2022)
