# Book settings
title: EMSC 2022
author: David Heslop, Meghan Miller, Louis Moresi 
logo: Figures/AuWorldEQ.jpg
exclude_patterns: ["README.md", "Notes/*", "Scripts/*, */ScratchPad/*", "Lectures/*reveal.md"]

latex:
  latex_documents:
    targetname: EMSC2022.tex

html:
#  home_page_in_navbar option: true
  use_repository_button: true

parse:
  myst_extended_syntax: true

sphinx:
  config:
    html_show_copyright: false
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # html_extra_path: ['Figures/Movies']


    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution


repository:
  url         : https://github.com/ANU-RSES-Education/EMSC-2022  # Online location of this book
  branch      : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  jupyterhub_url: "https://emsc2022-2021.rses.underworldcloud.org"  # The URL for your JupyterHub. 
  binderhub_url:  "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  notebook_interface: "classic" # "jupyterlab" or "classic"


execute:
  # exclude_patterns:
  #   - File.ipynb

  allow_errors : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  timeout: 240

  execute_notebooks: false
  # cache: .jupyter-cache 

  # bibtex_bibfiles:
  #  - JupyterBook.bib
