# Book settings
title: EMSC 2022
author: David Heslop, Meghan Miller, Louis Moresi 
logo: Figures/AuWorldEQ.jpg
exclude_patterns: ["README.md", "Notes/*", "Scripts/*, */ScratchPad/*", "Lectures/*reveal.md"]

latex:
  latex_documents:
    targetname: EMSC2022.tex

html:
#  home_page_in_navbar option: true
  extra_navbar: <button type="button" onclick="legibleFontSwitcher()">Switch Font</button>&nbsp;&nbsp;<button type="button" onclick="fontScaler(1.1)">&#10133;</button><button type="button" onclick="fontScaler(0.0)">&#9679;</button><button type="button" onclick="fontScaler(0.909)">&#10134;</button>  
  use_repository_button: true
  comments:
    hypothesis: true

# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_extra_path: ['Lectures/static_slides']
    bibtex_reference_style: author_year

    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution


repository:
  url         : https://github.com/ANU-RSES-Education/EMSC-2022  # Online location of this book
  # branch      : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  jupyterhub_url: "https://emsc2022.rses.underworldcloud.org"  # The URL for your JupyterHub. 
  binderhub_url:  "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  # notebook_interface: "classic" # "jupyterlab" or "classic"


execute:
  # exclude_patterns:
  #   - File.ipynb

  allow_errors : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  timeout: 240

  execute_notebooks: false
  # cache: .jupyter-cache 

  bibtex_bibfiles:
   - JupyterBook.bib
