
name: Update packages

on:
  push:
    paths:
      - packages.yml                          # or the list of packages
      - .github/workflows/update_packages.yml # or this file


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Install sshpass
      run: |
        sudo apt-get install -y sshpass
      

    # Runs a set of commands using the runners shell
    - name: Install conda packages from packages.yml file
      env:  
        SSHPASS: ${{ secrets.DROPLET_PASS }}
        
      run: |
        sudo -E sshpass -e ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "hostname"
        sudo -E sshpass -e scp packages.yml root@${{ secrets.DROPLET_IP }}:packages.yml
        sudo -E sshpass -e ssh root@${{ secrets.DROPLET_IP }} 'sudo -E /opt/tljh/user/bin/conda env update -n base --file packages.yml'
        sudo -E sshpass -e ssh root@${{ secrets.DROPLET_IP }} "sudo tljh-config reload hub"
